apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seema-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: seema
